# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: player_positions.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'player_positions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16player_positions.proto\x12\x10player_positions\"n\n\x0ePlayerPosition\x12\x11\n\tunique_id\x18\x01 \x01(\t\x12\x13\n\x0bplayer_name\x18\x02 \x01(\t\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01y\x18\x04 \x01(\x01\x12\t\n\x01x\x18\x05 \x01(\x01\x12\x13\n\x0bvehicle_key\x18\x06 \x01(\t\"D\n\x0fPlayerPositions\x12\x31\n\x07players\x18\x01 \x03(\x0b\x32 .player_positions.PlayerPositionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_positions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERPOSITION']._serialized_start=44
  _globals['_PLAYERPOSITION']._serialized_end=154
  _globals['_PLAYERPOSITIONS']._serialized_start=156
  _globals['_PLAYERPOSITIONS']._serialized_end=224
# @@protoc_insertion_point(module_scope)
