# Generated by Django 5.2.3 on 2025-07-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerchatlog",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
