# Generated by Django 5.2.3 on 2025-07-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0002_playerchatlog_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="discord_user_id",
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
    ]
