# Generated by Django 5.2.3 on 2025-07-10 08:01

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0005_vehicle_alter_playerchatlog_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timespan",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amc.character"
                    ),
                ),
            ],
        ),
    ]
