# Generated by Django 5.2.3 on 2025-07-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0006_playerstatuslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverlog",
            name="log_path",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
