# Generated by Django 5.2.3 on 2025-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0008_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverlog",
            name="event_processed",
            field=models.BooleanField(default=False),
        ),
    ]
