# Generated by Django 5.2.3 on 2025-07-12 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0010_playerstatuslog_original_log_playerrestockdepotlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="amc.player",
            ),
        ),
    ]
