# Generated by Django 5.2.3 on 2025-07-12 10:37

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0011_alter_character_player"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.AddField(
            model_name="playerstatuslog",
            name="duration",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("timespan__endswith"),
                    "-",
                    models.F("timespan__startswith"),
                ),
                output_field=models.DurationField(),
            ),
        ),
    ]
