# Generated by Django 5.2.3 on 2025-07-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0012_alter_company_options_playerstatuslog_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="bus_level",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="driver_level",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="police_level",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="racer_level",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="taxi_level",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="truck_level",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="wrecker_level",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
