# Generated by Django 5.2.3 on 2025-07-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0014_botinvocationlog_songrequestlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playerstatuslog",
            options={"ordering": ["-timespan__startswith"]},
        ),
        migrations.AlterField(
            model_name="botinvocationlog",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bot_invocation_logs",
                to="amc.character",
            ),
        ),
        migrations.AlterField(
            model_name="playerchatlog",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_logs",
                to="amc.character",
            ),
        ),
        migrations.AlterField(
            model_name="playerstatuslog",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="amc.character",
            ),
        ),
        migrations.AlterField(
            model_name="playervehiclelog",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_logs",
                to="amc.character",
            ),
        ),
        migrations.AlterField(
            model_name="songrequestlog",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="song_request_logs",
                to="amc.character",
            ),
        ),
    ]
