# Generated by Django 5.2.3 on 2025-07-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0016_playervehiclelog_vehicle_game_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playervehiclelog",
            name="vehicle_game_id",
            field=models.PositiveBigIntegerField(db_index=True, null=True),
        ),
    ]
