# Generated by Django 5.2.3 on 2025-07-18 08:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0017_alter_playervehiclelog_vehicle_game_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "guid",
                    models.CharField(db_index=True, editable=False, max_length=32),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("state", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RaceSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config", models.JSONField(blank=True, null=True)),
                ("hash", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameEventCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("laps", models.IntegerField(default=0)),
                ("section_index", models.IntegerField(default=-1)),
                ("last_section_total_time_seconds", models.FloatField()),
                ("best_lap_time", models.FloatField()),
                (
                    "lap_times",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
                ("wrong_engine", models.BooleanField()),
                ("wrong_vehicle", models.BooleanField()),
                ("disqualified", models.BooleanField()),
                ("finished", models.BooleanField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amc.character"
                    ),
                ),
                (
                    "game_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amc.gameevent"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gameevent",
            name="characters",
            field=models.ManyToManyField(
                related_name="game_events",
                through="amc.GameEventCharacter",
                to="amc.character",
            ),
        ),
        migrations.CreateModel(
            name="LapSectionTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_index", models.IntegerField()),
                ("lap", models.IntegerField()),
                ("rank", models.IntegerField()),
                ("total_time_seconds", models.FloatField()),
                (
                    "game_event_character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lap_section_times",
                        to="amc.gameeventcharacter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gameevent",
            name="race_setup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game_events",
                to="amc.racesetup",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "discord_event_id",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                (
                    "discord_thread_id",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                (
                    "race_setup",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_events",
                        to="amc.racesetup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gameevent",
            name="scheduled_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game_events",
                to="amc.scheduledevent",
            ),
        ),
        migrations.CreateModel(
            name="ScheduledEventPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amc.player"
                    ),
                ),
                (
                    "scheduled_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amc.scheduledevent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scheduledevent",
            name="players",
            field=models.ManyToManyField(
                related_name="scheduled_events",
                through="amc.ScheduledEventPlayer",
                to="amc.player",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameeventcharacter",
            constraint=models.UniqueConstraint(
                fields=("character", "game_event"), name="unique_character_game_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="lapsectiontime",
            constraint=models.UniqueConstraint(
                fields=("game_event_character", "section_index", "lap"),
                name="unique_event_lap_section_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledeventplayer",
            constraint=models.UniqueConstraint(
                fields=("player", "scheduled_event"),
                name="unique_player_scheduled_event",
            ),
        ),
    ]
