# Generated by Django 5.2.3 on 2025-07-18 09:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0018_gameevent_racesetup_gameeventcharacter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(dim=3, srid=0),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="amc.character",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("timestamp", "character"),
                        name="unique_character_location",
                    )
                ],
            },
        ),
    ]
