# Generated by Django 5.2.3 on 2025-07-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0019_characterlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerMailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "received_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "from_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_messages",
                        to="amc.player",
                    ),
                ),
                (
                    "to_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbox_messages",
                        to="amc.player",
                    ),
                ),
            ],
        ),
    ]
