# Generated by Django 5.2.3 on 2025-07-20 14:40

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0020_playermailmessage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="serverlog",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("text", config="english"),
                name="log_text_search_idx",
            ),
        ),
    ]
