# Generated by Django 5.2.3 on 2025-07-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0027_team_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="racing",
            field=models.BooleanField(default=True),
        ),
    ]
