# Generated by Django 5.2.3 on 2025-07-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0028_team_racing"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledevent",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="team_logos"),
        ),
    ]
