# Generated by Django 5.2.3 on 2025-07-27 16:59

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0030_alter_gameeventcharacter_best_lap_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championshippoint",
            name="participant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="championship_point",
                to="amc.gameeventcharacter",
            ),
        ),
        migrations.AlterField(
            model_name="gameeventcharacter",
            name="net_time",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("last_section_total_time_seconds"),
                    "-",
                    models.F("first_section_total_time_seconds"),
                ),
                output_field=models.FloatField(blank=True, null=True),
            ),
        ),
    ]
