# Generated by Django 5.2.3 on 2025-07-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0032_serverlog_hostname_serverlog_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledevent",
            name="time_trial",
            field=models.BooleanField(default=False),
        ),
    ]
