# Generated by Django 5.2.3 on 2025-07-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0033_scheduledevent_time_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="racesetup",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
