# Generated by Django 5.2.3 on 2025-07-28 13:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0036_deliverypoint_data_deliverypoint_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameeventcharacter",
            name="lap_times",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
