# Generated by Django 5.2.3 on 2025-07-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0037_alter_gameeventcharacter_lap_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="adminstrator",
            field=models.BooleanField(default=False),
        ),
    ]
