# Generated by Django 5.2.3 on 2025-07-31 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0038_player_adminstrator"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameevent",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="amc.character",
            ),
        ),
    ]
