# Generated by Django 5.2.3 on 2025-07-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0039_gameevent_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="guid",
            field=models.CharField(
                editable=False, max_length=32, null=True, unique=True
            ),
        ),
    ]
