# Generated by Django 5.2.3 on 2025-08-05 05:14

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0042_gameeventcharacter_penalty_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameeventcharacter",
            name="net_time_with_penalty",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    django.db.models.expressions.CombinedExpression(
                        models.F("last_section_total_time_seconds"),
                        "-",
                        models.F("first_section_total_time_seconds"),
                    ),
                    "+",
                    models.F("penalty_seconds"),
                ),
                output_field=models.FloatField(blank=True, null=True),
            ),
        ),
    ]
