# Generated by Django 5.2.3 on 2025-08-05 05:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0043_gameeventcharacter_net_time_with_penalty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameeventcharacter",
            name="net_time",
        ),
        migrations.RenameField(
            model_name="gameeventcharacter",
            old_name="net_time_with_penalty",
            new_name="net_time",
        ),
    ]
