# Generated by Django 5.2.3 on 2025-08-05 05:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0044_remove_gameeventcharacter_net_time_with_penalty_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameeventcharacter",
            options={
                "ordering": [
                    "disqualified",
                    "-finished",
                    "-laps",
                    "-section_index",
                    "net_time",
                ]
            },
        ),
    ]
