# Generated by Django 5.2.3 on 2025-08-06 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0046_servercargoarrivedlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerSignContractLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("cargo_key", models.CharField(db_index=True, max_length=200)),
                ("amount", models.FloatField()),
                ("cost", models.PositiveIntegerField()),
                ("payment", models.PositiveIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts_signed",
                        to="amc.player",
                    ),
                ),
            ],
        ),
    ]
