# Generated by Django 5.2.3 on 2025-08-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0047_serversigncontractlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="serversigncontractlog",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
    ]
