# Generated by Django 5.2.3 on 2025-08-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0048_serversigncontractlog_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="servercargoarrivedlog",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
