# Generated by Django 5.2.3 on 2025-08-10 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0050_character_saving_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerPassengerArrivedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "passenger_type",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Hitchhiker"),
                            (2, "Taxi"),
                            (3, "Ambulance"),
                            (4, "Bus"),
                        ],
                        db_index=True,
                    ),
                ),
                ("distance", models.FloatField()),
                ("payment", models.PositiveIntegerField()),
                ("arrived", models.BooleanField(default=True)),
                (
                    "player",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passengers_delivered",
                        to="amc.player",
                    ),
                ),
            ],
        ),
    ]
