# Generated by Django 5.2.3 on 2025-08-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0051_serverpassengerarrivedlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverpassengerarrivedlog",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
