# Generated by Django 5.2.3 on 2025-08-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0053_serversigncontractlog_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="money",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
