# Generated by Django 5.2.3 on 2025-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0058_scheduledevent_staggered_start_delay"),
    ]

    operations = [
        migrations.AddField(
            model_name="championshippoint",
            name="prize",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
