# Generated by Django 5.2.3 on 2025-08-24 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0060_character_reject_ubi_character_ubi_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="servercargoarrivedlog",
            name="destination_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries_in",
                to="amc.deliverypoint",
            ),
        ),
        migrations.AddField(
            model_name="servercargoarrivedlog",
            name="sender_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries_out",
                to="amc.deliverypoint",
            ),
        ),
    ]
