# Generated by Django 5.2.3 on 2025-08-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0061_servercargoarrivedlog_destination_point_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledevent",
            name="initial_offset",
            field=models.IntegerField(
                default=1000, help_text="Gap between starting line and first row"
            ),
        ),
        migrations.AddField(
            model_name="scheduledevent",
            name="lateral_spacing",
            field=models.IntegerField(
                default=600, help_text="Horizonal spacing between starting grid"
            ),
        ),
        migrations.AddField(
            model_name="scheduledevent",
            name="longitudinal_spacing",
            field=models.IntegerField(
                default=1000, help_text="Vertical spacing between starting grid"
            ),
        ),
        migrations.AddField(
            model_name="scheduledevent",
            name="pole_side_right",
            field=models.BooleanField(
                default=True,
                help_text="If true, the first position is on the right side",
            ),
        ),
        migrations.AddField(
            model_name="scheduledevent",
            name="reverse_starting_direction",
            field=models.BooleanField(
                default=False,
                help_text="If true, the starting grid will be on the opposite side of the starting line",
            ),
        ),
    ]
