# Generated by Django 5.2.3 on 2025-08-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0064_vehicledealership"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverpassengerarrivedlog",
            name="comfort",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="serverpassengerarrivedlog",
            name="comfort_rating",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="serverpassengerarrivedlog",
            name="limo",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="serverpassengerarrivedlog",
            name="offroad",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="serverpassengerarrivedlog",
            name="urgent",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="serverpassengerarrivedlog",
            name="urgent_rating",
            field=models.IntegerField(null=True),
        ),
    ]
