# Generated by Django 5.2.3 on 2025-09-14 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0066_thank"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo_key", models.CharField(db_index=True, max_length=200)),
                ("quantity_requested", models.PositiveIntegerField()),
                ("quantity_fulfilled", models.PositiveIntegerField(default=0)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("expired_at", models.DateTimeField()),
                ("bonus_multiplier", models.FloatField()),
                (
                    "destination_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs_in",
                        to="amc.deliverypoint",
                    ),
                ),
                (
                    "source_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs_out",
                        to="amc.deliverypoint",
                    ),
                ),
            ],
        ),
    ]
