# Generated by Django 5.2.3 on 2025-09-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0067_deliveryjob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryjob",
            name="destination_point",
        ),
        migrations.RemoveField(
            model_name="deliveryjob",
            name="source_point",
        ),
        migrations.AddField(
            model_name="deliveryjob",
            name="destination_points",
            field=models.ManyToManyField(
                related_name="jobs_in", to="amc.deliverypoint"
            ),
        ),
        migrations.AddField(
            model_name="deliveryjob",
            name="source_points",
            field=models.ManyToManyField(
                related_name="jobs_out", to="amc.deliverypoint"
            ),
        ),
    ]
