# Generated by Django 5.2.3 on 2025-09-16 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0068_remove_deliveryjob_destination_point_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverypoint",
            options={"ordering": ["name"]},
        ),
    ]
