# Generated by Django 5.2.3 on 2025-09-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0069_alter_deliverypoint_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryjob",
            name="discord_message_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
