# Generated by Django 5.2.3 on 2025-09-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0071_alter_deliveryjob_cargo_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryjob",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deliveryjob",
            name="destination_points",
            field=models.ManyToManyField(
                blank=True, related_name="jobs_in", to="amc.deliverypoint"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryjob",
            name="discord_message_id",
            field=models.PositiveBigIntegerField(
                blank=True, help_text="For bot use only, leave blank", null=True
            ),
        ),
        migrations.AlterField(
            model_name="deliveryjob",
            name="source_points",
            field=models.ManyToManyField(
                blank=True, related_name="jobs_out", to="amc.deliverypoint"
            ),
        ),
    ]
