# Generated by Django 5.2.3 on 2025-09-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0072_deliveryjob_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryjob",
            name="completion_bonus",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
