# Generated by Django 5.2.3 on 2025-09-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0077_alter_deliveryjob_cargo_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverypoint",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
