# Generated by Django 5.2.3 on 2025-09-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0078_alter_deliverypoint_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="notes",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="social_score",
            field=models.IntegerField(default=0),
        ),
    ]
