# Generated by Django 5.2.3 on 2025-09-22 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0085_alter_company_money"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "infringement",
                    models.CharField(
                        choices=[
                            ("cluterring", "Cluterring"),
                            ("griefing", "Griefing"),
                            ("trolling", "Trolling"),
                            ("other", "Other"),
                        ],
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="amc.character",
                    ),
                ),
            ],
        ),
    ]
