# Generated by Django 5.2.3 on 2025-09-23 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0086_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypointstorage",
            name="cargo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storages",
                to="amc.cargo",
            ),
        ),
    ]
