# Generated by Django 5.2.3 on 2025-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0089_serverstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypointstorage",
            name="capacity",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
