# Generated by Django 5.2.3 on 2025-09-26 03:33

import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0090_deliverypointstorage_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryjob",
            name="fulfilled",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.lookups.GreaterThanOrEqual(
                    models.F("quantity_fulfilled"), models.F("quantity_requested")
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
