# Generated by Django 5.2.3 on 2025-09-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0091_deliveryjob_fulfilled"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryjob",
            name="fulfilled_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
