# Generated by Django 5.2.3 on 2025-09-28 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0096_deliveryjob_template_job_period_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtypes",
                to="amc.cargo",
            ),
        ),
    ]
