# Generated by Django 5.2.3 on 2025-09-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0097_cargo_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverypointstorage",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
