# Generated by Django 5.2.3 on 2025-10-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0099_alter_ticket_infringement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="guid",
            field=models.CharField(
                editable=False, max_length=32, null=True, unique=True
            ),
        ),
    ]
