# Generated by Django 5.2.3 on 2025-10-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0100_alter_character_guid"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverstatus",
            name="used_memory",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
