# Generated by Django 5.2.3 on 2025-10-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0101_serverstatus_used_memory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverstatus",
            name="used_memory",
            field=models.PositiveBigIntegerField(),
        ),
    ]
