# Generated by Django 5.2.3 on 2025-10-04 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0102_alter_serverstatus_used_memory"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryjob",
            name="base_template",
            field=models.ForeignKey(
                blank=True,
                help_text="The template this job was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="amc.deliveryjob",
            ),
        ),
    ]
