# Generated by Django 5.2.3 on 2025-10-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0103_deliveryjob_base_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="suspect",
            field=models.BooleanField(default=False),
        ),
    ]
