# Generated by Django 5.2.3 on 2025-10-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0104_player_suspect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembership",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="amc.player",
            ),
        ),
    ]
