# Generated by Django 5.2.3 on 2025-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0105_alter_teammembership_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverstatus",
            name="num_players",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
