# Generated by Django 5.2.3 on 2025-10-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0108_deliveryjob_rp_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDecal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("config", models.JSONField(blank=True, null=True)),
                ("hash", models.CharField(max_length=200, unique=True)),
                ("vehicle_key", models.CharField(max_length=100, null=True)),
                ("private", models.BooleanField(default=True)),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decals",
                        to="amc.player",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hash", "player"), name="unique_player_decal_hash"
                    ),
                    models.UniqueConstraint(
                        fields=("name", "player"), name="unique_player_decal_name"
                    ),
                ],
            },
        ),
    ]
