# Generated by Django 5.2.3 on 2025-10-16 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0109_vehicledecal"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time_utc",
                    models.TimeField(
                        help_text="The start time of the user's shift in UTC."
                    ),
                ),
                (
                    "end_time_utc",
                    models.TimeField(
                        help_text="The end time of the user's shift in UTC."
                    ),
                ),
                (
                    "user_timezone",
                    models.CharField(
                        default="UTC",
                        help_text="The user's local timezone (e.g., 'America/New_York').",
                        max_length=100,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shifts",
                        to="amc.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RescueRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(blank=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rescue_requests",
                        to="amc.character",
                    ),
                ),
            ],
        ),
    ]
