# Generated by Django 5.2.3 on 2025-10-30 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0112_character_custom_name_alter_character_bus_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammembership",
            name="character",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_memberships",
                to="amc.character",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_memberships",
                to="amc.player",
            ),
        ),
    ]
