# Generated by Django 5.2.3 on 2025-10-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0113_teammembership_character_alter_teammembership_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="rp_mode",
            field=models.BooleanField(default=False),
        ),
    ]
