# Generated by Django 5.2.3 on 2025-11-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0116_scheduledevent_description_in_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="rp_mode",
            field=models.BooleanField(default=False),
        ),
    ]
