# Generated by Django 5.2.3 on 2025-11-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0117_character_rp_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="actor_class_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
