# Generated by Django 5.2.3 on 2025-11-05 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0118_vehicle_actor_class_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="actor_class_name",
        ),
    ]
