# Generated by Django 5.2.3 on 2025-11-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0121_remove_charactervehicle_unique_character_vehicle_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactervehicle",
            name="spawn_on_restart",
            field=models.BooleanField(default=False),
        ),
    ]
