# Generated by Django 5.2.3 on 2025-11-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0123_company_guid_company_has_tp_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactervehicle",
            name="rental",
            field=models.BooleanField(default=False),
        ),
    ]
