# Generated by Django 5.2.3 on 2025-11-14 19:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0124_charactervehicle_rental"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="loan_repayment_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("1.00")),
                ],
            ),
        ),
    ]
