# Generated by Django 5.2.3 on 2025-11-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0125_character_loan_repayment_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactervehicle",
            name="for_sale",
            field=models.BooleanField(default=False),
        ),
    ]
