# Generated by Django 5.2.3 on 2025-11-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0126_charactervehicle_for_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactervehicle",
            name="alias",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
