# Generated by Django 5.2.3 on 2025-11-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0127_charactervehicle_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="displayer",
            field=models.BooleanField(
                default=False, help_text="Livery artists, showcase etc"
            ),
        ),
    ]
