# Generated by Django 5.2.3 on 2025-11-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0129_garage"),
    ]

    operations = [
        migrations.AddField(
            model_name="garage",
            name="tag",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
