# Generated by Django 5.2.3 on 2025-11-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0131_alter_characterlocation_vehicle_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        help_text="The text to display (e.g., PANZER)", max_length=255
                    ),
                ),
                ("location_x", models.FloatField(help_text="World X Coordinate")),
                ("location_y", models.FloatField(help_text="World Y Coordinate")),
                ("location_z", models.FloatField(help_text="World Z Coordinate")),
                (
                    "yaw",
                    models.FloatField(
                        default=0.0, help_text="Rotation in degrees (0=X+, 90=Y+)"
                    ),
                ),
                (
                    "scale",
                    models.FloatField(default=5.0, help_text="Uniform scale factor"),
                ),
                (
                    "separation",
                    models.FloatField(
                        default=30.0,
                        help_text="Distance between letters relative to scale",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
