# Generated by Django 5.2.3 on 2025-11-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0132_worldtext"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_path",
                    models.CharField(help_text="The asset path", max_length=511),
                ),
                ("location_x", models.FloatField(help_text="World X Coordinate")),
                ("location_y", models.FloatField(help_text="World Y Coordinate")),
                ("location_z", models.FloatField(help_text="World Z Coordinate")),
                (
                    "yaw",
                    models.FloatField(
                        default=0.0, help_text="Rotation in degrees (0=X+, 90=Y+)"
                    ),
                ),
                (
                    "scale",
                    models.FloatField(default=1.0, help_text="Uniform scale factor"),
                ),
            ],
        ),
    ]
