# Generated by Django 5.2.3 on 2025-12-25 06:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0134_player_language_alter_characterlocation_vehicle_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubsidyArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(srid=3857),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="deliverypoint",
            name="coord",
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=3857),
        ),
        migrations.CreateModel(
            name="SubsidyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher number = evaluated first"
                    ),
                ),
                ("requires_on_time", models.BooleanField(default=False)),
                (
                    "reward_type",
                    models.CharField(
                        choices=[("PERCENTAGE", "Percentage"), ("FLAT", "Flat Amount")],
                        max_length=20,
                    ),
                ),
                (
                    "reward_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (e.g. 3.0 for 300%) or Flat Amount",
                        max_digits=12,
                    ),
                ),
                (
                    "scales_with_damage",
                    models.BooleanField(
                        default=False,
                        help_text="If true, multiplies reward by health %",
                    ),
                ),
                (
                    "cargos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If empty, applies to ALL cargos",
                        to="amc.cargo",
                    ),
                ),
                (
                    "destination_areas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="destination_rules",
                        to="amc.subsidyarea",
                    ),
                ),
                (
                    "source_areas",
                    models.ManyToManyField(
                        blank=True, related_name="source_rules", to="amc.subsidyarea"
                    ),
                ),
            ],
        ),
    ]
