# Generated by Django 5.2.3 on 2025-12-25 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0137_populate_subsidies"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryJobTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Give the template a name", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "default_quantity",
                    models.PositiveIntegerField(help_text="Default quantity requested"),
                ),
                ("bonus_multiplier", models.FloatField(default=1.0)),
                ("completion_bonus", models.PositiveIntegerField(default=50000)),
                (
                    "rp_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Requires the job to be done in RP mode",
                    ),
                ),
                (
                    "expected_player_count_for_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="When player count is lower than this, quantity will be scaled down",
                        null=True,
                    ),
                ),
                (
                    "job_posting_probability",
                    models.FloatField(
                        default=1.0,
                        help_text="The probability at which the job is posted. Defaults to 100% (1.0)",
                    ),
                ),
                (
                    "duration_hours",
                    models.FloatField(
                        default=5.0, help_text="The number of hours to complete the job"
                    ),
                ),
                (
                    "cargos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Use either Cargo Key or this field for multiple cargo types",
                        related_name="job_templates",
                        to="amc.cargo",
                    ),
                ),
                (
                    "destination_points",
                    models.ManyToManyField(
                        blank=True,
                        related_name="job_templates_in",
                        to="amc.deliverypoint",
                    ),
                ),
                (
                    "source_points",
                    models.ManyToManyField(
                        blank=True,
                        related_name="job_templates_out",
                        to="amc.deliverypoint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deliveryjob",
            name="created_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="amc.deliveryjobtemplate",
            ),
        ),
    ]
