# Generated by Django 5.2.3 on 2025-12-25 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0139_migrate_delivery_job_templates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryjob",
            name="base_template",
        ),
        migrations.RemoveField(
            model_name="deliveryjob",
            name="expected_player_count_for_quantity",
        ),
        migrations.RemoveField(
            model_name="deliveryjob",
            name="job_posting_probability",
        ),
        migrations.RemoveField(
            model_name="deliveryjob",
            name="template",
        ),
        migrations.RemoveField(
            model_name="deliveryjob",
            name="template_job_period_hours",
        ),
    ]
