# Generated by Django 5.2.3 on 2025-12-25 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0141_deliveryjob_escrowed_amount_ministryterm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinistryElection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("candidacy_end_at", models.DateTimeField()),
                ("poll_end_at", models.DateTimeField()),
                (
                    "term_created",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="election",
                        to="amc.ministryterm",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elections_won",
                        to="amc.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinistryCandidacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("manifesto", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministry_candidacies",
                        to="amc.player",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="amc.ministryelection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ministry Candidacies",
                "unique_together": {("election", "candidate")},
            },
        ),
        migrations.CreateModel(
            name="MinistryVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="amc.ministrycandidacy",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="amc.ministryelection",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministry_votes",
                        to="amc.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("election", "voter")},
            },
        ),
    ]
