# Generated by Django 5.2.3 on 2025-12-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0142_ministryelection_ministrycandidacy_ministryvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="ministryelection",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subsidyrule",
            name="allocation",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ministry allocated budget for this rule",
                max_digits=16,
            ),
        ),
        migrations.AddField(
            model_name="subsidyrule",
            name="spent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount spent from the allocation",
                max_digits=16,
            ),
        ),
    ]
