# Generated by Django 5.2.3 on 2025-12-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0143_ministryelection_is_processed_subsidyrule_allocation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinistryDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ministry Dashboard",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="playervehiclelog",
            options={"ordering": ["-timestamp"]},
        ),
    ]
