# Generated by Django 5.2.3 on 2025-12-28 12:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0144_ministrydashboard_alter_playervehiclelog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescuerequest",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, dim=3, null=True, srid=0
            ),
        ),
    ]
