# Generated by Django 5.2.3 on 2026-03-14 10:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Required for CREATE INDEX CONCURRENTLY

    dependencies = [
        ("amc", "0146_deliverypoint_sync"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE "amc_character" ADD COLUMN IF NOT EXISTS "last_location" geometry(POINTZ, 0);
                ALTER TABLE "amc_character" ADD COLUMN IF NOT EXISTS "last_vehicle_key" varchar(100);
            """,
            reverse_sql="""
                ALTER TABLE "amc_character" DROP COLUMN IF EXISTS "last_location";
                ALTER TABLE "amc_character" DROP COLUMN IF EXISTS "last_vehicle_key";
            """,
            state_operations=[
                migrations.AddField(
                    model_name="character",
                    name="last_location",
                    field=django.contrib.gis.db.models.fields.PointField(
                        blank=True, dim=3, null=True, srid=0
                    ),
                ),
                migrations.AddField(
                    model_name="character",
                    name="last_vehicle_key",
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql='CREATE INDEX CONCURRENTLY IF NOT EXISTS "charloc_char_ts_idx" ON "amc_characterlocation" ("character_id", "timestamp" DESC)',
            reverse_sql='DROP INDEX CONCURRENTLY IF EXISTS "charloc_char_ts_idx"',
            state_operations=[
                migrations.AddIndex(
                    model_name="characterlocation",
                    index=models.Index(
                        fields=["character", "-timestamp"], name="charloc_char_ts_idx"
                    ),
                ),
            ],
        ),
    ]
