# Generated by Django 5.2.3 on 2026-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0150_character_last_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="total_donations",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
