from django.db import migrations


MONTHS = [
    ("2025_07", "2025-07-01", "2025-08-01"),
    ("2025_08", "2025-08-01", "2025-09-01"),
    ("2025_09", "2025-09-01", "2025-10-01"),
    ("2025_10", "2025-10-01", "2025-11-01"),
    ("2025_11", "2025-11-01", "2025-12-01"),
    ("2025_12", "2025-12-01", "2026-01-01"),
    ("2026_01", "2026-01-01", "2026-02-01"),
    ("2026_02", "2026-02-01", "2026-03-01"),
    ("2026_03", "2026-03-01", "2026-04-01"),
    ("2026_04", "2026-04-01", "2026-05-01"),
    ("2026_05", "2026-05-01", "2026-06-01"),
    ("2026_06", "2026-06-01", "2026-07-01"),
]


def build_forward_sql():
    parts = []

    # 1. Create partitioned table
    parts.append("""\
CREATE TABLE amc_characterlocation_new (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    "timestamp" timestamptz NOT NULL,
    character_id integer NOT NULL,
    location geometry(PointZ) NOT NULL,
    vehicle_key varchar(100),
    CONSTRAINT pk_charloc_new PRIMARY KEY (id, "timestamp")
) PARTITION BY RANGE ("timestamp");
""")

    # 2. Create monthly partitions
    for suffix, start, end in MONTHS:
        parts.append(
            f"CREATE TABLE amc_charloc_p{suffix} PARTITION OF amc_characterlocation_new "
            f"FOR VALUES FROM ('{start}') TO ('{end}');"
        )

    # Default partition for anything outside the defined ranges
    parts.append(
        "CREATE TABLE amc_charloc_default "
        "PARTITION OF amc_characterlocation_new DEFAULT;"
    )

    # 3. Create indexes (auto-inherited by partitions)
    parts.append(
        "CREATE INDEX charloc_new_char_ts_idx "
        'ON amc_characterlocation_new (character_id, "timestamp" DESC);'
    )

    # 4. FK constraint
    parts.append(
        "ALTER TABLE amc_characterlocation_new "
        "ADD CONSTRAINT fk_charloc_new_character "
        "FOREIGN KEY (character_id) REFERENCES amc_character(id) ON DELETE CASCADE;"
    )

    # 5. Unique constraint (partition key must be included)
    parts.append(
        "ALTER TABLE amc_characterlocation_new "
        'ADD CONSTRAINT unique_character_location_new UNIQUE ("timestamp", character_id);'
    )

    # 6. Dual-write trigger
    parts.append("""\
CREATE OR REPLACE FUNCTION charloc_dual_write() RETURNS trigger AS $$
BEGIN
    INSERT INTO amc_characterlocation_new (id, "timestamp", character_id, location, vehicle_key)
    VALUES (NEW.id, NEW."timestamp", NEW.character_id, NEW.location, NEW.vehicle_key)
    ON CONFLICT ("timestamp", character_id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER charloc_dual_write_trigger
    AFTER INSERT ON amc_characterlocation
    FOR EACH ROW EXECUTE FUNCTION charloc_dual_write();
""")

    return "\n".join(parts)


def build_reverse_sql():
    return """\
DROP TRIGGER IF EXISTS charloc_dual_write_trigger ON amc_characterlocation;
DROP FUNCTION IF EXISTS charloc_dual_write();
DROP TABLE IF EXISTS amc_characterlocation_new CASCADE;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0153_jobpostingconfig"),
    ]

    operations = [
        migrations.RunSQL(
            sql=build_forward_sql(),
            reverse_sql=build_reverse_sql(),
        ),
    ]
