# Generated by Django 5.2.3 on 2026-03-15 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0154_partition_characterlocation_setup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpostingconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="jobpostingconfig",
            name="players_per_job",
            field=models.IntegerField(
                default=10,
                help_text="Base formula: 1 job per N players",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
