# Generated by Django 5.2.3 on 2026-03-17 12:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0161_add_template_success_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplyChainEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "total_prize",
                    models.PositiveBigIntegerField(
                        help_text="Total reward pool escrowed from treasury"
                    ),
                ),
                (
                    "per_delivery_bonus_pct",
                    models.FloatField(
                        default=0.2,
                        help_text="Fraction of total prize allocated to per-delivery bonuses (e.g. 0.20 = 20%)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "escrowed_amount",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Amount held from treasury"
                    ),
                ),
                ("rewards_distributed", models.BooleanField(default=False)),
                (
                    "discord_message_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_at__lt", models.F("end_at"))),
                        name="supply_chain_event_start_before_end",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplyChainObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ceiling",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Max rewardable quantity. Null = uncapped.",
                        null=True,
                    ),
                ),
                ("quantity_fulfilled", models.PositiveIntegerField(default=0)),
                (
                    "reward_weight",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Relative weight for reward pool share (e.g. 40 for 40%)",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary objectives define the main event goal",
                    ),
                ),
                (
                    "per_delivery_bonus_multiplier",
                    models.FloatField(
                        default=0.0,
                        help_text="Multiplier on per-delivery bonus. 0 = no per-delivery bonus for this objective.",
                    ),
                ),
                (
                    "cargos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="supply_chain_objectives",
                        to="amc.cargo",
                    ),
                ),
                (
                    "destination_points",
                    models.ManyToManyField(
                        blank=True,
                        related_name="supply_chain_objectives_in",
                        to="amc.deliverypoint",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="amc.supplychainevent",
                    ),
                ),
                (
                    "source_points",
                    models.ManyToManyField(
                        blank=True,
                        related_name="supply_chain_objectives_out",
                        to="amc.deliverypoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplyChainContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo_key",
                    models.CharField(
                        choices=[
                            ("SmallBox", "Small Box"),
                            ("CarrotBox", "Carrots"),
                            ("AppleBox", "Apples"),
                            ("OrangeBox", "Oranges"),
                            ("GlassBottleBox", "Glass Bottle"),
                            ("BoxPallete_01", "Box Pallet A"),
                            ("GroceryBox", "Grocery Box"),
                            ("GroceryBag", "Grocery Bag"),
                            ("BoxPallete_02", "Box Pallet B"),
                            ("BoxPallete_03", "Box Pallet C"),
                            ("PlasticPallete", "Plastic Pallet"),
                            ("PowerBox", "Power Box"),
                            ("ToyBoxes", "Toy Pallete"),
                            ("BottlePallete", "Water Bottle Pallet"),
                            ("WoodPlank_14ft_5t", "WoodPlank 14ft 5t"),
                            ("Container_30ft_5t", "Container 30ft 5t"),
                            ("Container_30ft_10t", "Container 30ft 10t"),
                            ("Container_30ft_20t", "Container 30ft 20t"),
                            ("Container_20ft_01", "Container 20ft"),
                            ("Container_40ft_01", "Container 40ft"),
                            ("Log_30ft_30t", "Log 30ft 30t"),
                            ("Log_Oak_12ft", "Oak Log 12ft"),
                            ("Log_Oak_24ft", "Oak Log 24ft"),
                            ("Log_20ft", "Log 20ft"),
                            ("Sand", "Sand"),
                            ("FineSand", "Fine Sand"),
                            ("Coal", "Coal"),
                            ("LimestoneRock", "Limestone Rock"),
                            ("Limestone", "Limestone"),
                            ("QuicklimePallet", "Quicklime Pallet"),
                            ("IronOre", "Iron Ore"),
                            ("Concrete", "Concrete"),
                            ("Fuel", "Fuel"),
                            ("Oil", "Oil"),
                            ("CrudeOil", "Crude Oil"),
                            ("LiveFish_01", "Live Fish"),
                            ("TrashBag", "Trash Bag"),
                            ("Trash_Big", "Trash Bag"),
                            ("Sofa_01", "Sofa A"),
                            ("Sofa_02", "Sofa B"),
                            ("Sofa_03", "Sofa C"),
                            ("Sofa_04", "Sofa D"),
                            ("Bed_01", "Bed A"),
                            ("Bed_02", "Bed B"),
                            ("Bed_03", "Bed C"),
                            ("Pizza_01", "Pizza 1 Box"),
                            ("Pizza_02", "Pizza 2 Box"),
                            ("Pizza_03", "Pizza 3 Box"),
                            ("Pizza_04", "Pizza 4 Box"),
                            ("Pizza_05", "Pizza 5 Box"),
                            ("Pizza_01_Premium", "Premium Pizza 1 Box"),
                            ("Burger_01", "Burger"),
                            ("Burger_01_Signature", "Signature Burger"),
                            ("MilitarySupplyBox_01_Empty", "Empty Supply Box"),
                            ("MilitarySupplyBox_01", "Supply Box"),
                            ("Rice", "Rice"),
                            ("OrangeBoxes", "Orange Pallet"),
                            ("RicePallet", "Rice Pallet"),
                            ("PumpkinBox", "Pumpkin Box"),
                            ("PumpkinPallet", "Pumpkin Pallet"),
                            ("CornBox", "Corn Box"),
                            ("CornPallet", "Corn Pallet"),
                            ("BeanPallet", "Bean Pallet"),
                            ("HempPallet", "Hemp Pallet"),
                            ("CabbagePallet", "Cabbage Pallet"),
                            ("ChilliPallet", "Chilli Pallet"),
                            ("PotatoPallet", "Potato Pallet"),
                            ("CheesePallet", "Cheese Pallet"),
                            ("CheeseBox", "Cheese Box"),
                            ("Milk", "Milk"),
                            ("MeatBox", "Meat Box"),
                            ("BreadBox", "Bread Box"),
                            ("BreadPallet", "Bread Pallet"),
                            ("AirlineMealPallet", "Airline Meal Pallet"),
                            ("SnackBox", "Snack Box"),
                            ("GiftBox_01", "Gift Box"),
                            ("FormulaSCM", "Formula SCM"),
                            ("PlasticPipes_6m", "Plastic Pipes 6m"),
                            ("lHBeam_6m", "H-Beam 6m"),
                            ("SteelCoil_10t", "Steel Coil"),
                            ("Cement", "Cement"),
                            ("Terra", "Terra"),
                            ("SunflowerSeed", "Sunflower Seed"),
                        ],
                        db_index=True,
                        max_length=200,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField()),
                (
                    "bonus_paid",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Per-delivery bonus amount paid"
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supply_chain_contributions",
                        to="amc.character",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supply_chain_contributions",
                        to="amc.delivery",
                    ),
                ),
                (
                    "objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="amc.supplychainobjective",
                    ),
                ),
            ],
        ),
    ]
