# Generated by Django 5.2.3 on 2026-03-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0164_supply_chain_per_item_payout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortcutzone",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
