# Generated by Django 5.2.3 on 2026-03-27 04:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0179_confiscation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrestZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
