# Generated by Django 5.2.3 on 2026-03-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0180_arrestzone"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="criminal_laundered_total",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
