# Generated by Django 5.2.3 on 2026-03-27 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0182_policesession_police_confiscated_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confiscation',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confiscations_received', to='amc.character'),
        ),
    ]
