# Generated by Django 5.2.3 on 2026-03-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0183_alter_confiscation_character'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='policesession',
            new_name='amc_polices_charact_482ce7_idx',
            old_name='amc_polices_charact_idx',
        ),
        migrations.AlterField(
            model_name='confiscation',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confiscations_made', to='amc.character'),
        ),
        migrations.AlterField(
            model_name='policesession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
