# Generated by Django 5.2.3 on 2026-04-05 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0188_wanted_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wanted",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wanted_records",
                to="amc.character",
            ),
        ),
    ]
