# Generated by Django 5.2.3 on 2026-04-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0190_delivery_wanted_alter_delivery_cargo_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanted',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
