# Generated by Django 5.2.3 on 2026-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0193_criminal_record_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='jailed_at',
            field=models.DateTimeField(blank=True, help_text='Set when the player is teleported to jail. Boundary enforcement stops after JAIL_DURATION_SECONDS (30 s).', null=True),
        ),
    ]
