# Generated by Django 5.2.3 on 2026-04-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0194_character_jailed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='jailed_at',
        ),
        migrations.AddField(
            model_name='character',
            name='jailed_until',
            field=models.DateTimeField(blank=True, help_text='Set when the player is teleported to jail. Boundary enforcement stops at this timestamp.', null=True),
        ),
    ]
