# Generated by Django 5.2.3 on 2026-04-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0200_alter_delivery_cargo_key_alter_deliveryjob_cargo_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactervehicle',
            name='is_world_vehicle',
            field=models.BooleanField(default=False, help_text='Apply decal/parts to all vehicles of this class in the world on restart (no spawning)'),
        ),
    ]
