# Generated by Django 5.2.3 on 2026-04-24 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0202_charactervehicle_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanted',
            name='set_by',
            field=models.ForeignKey(blank=True, help_text='Police officer who set this wanted status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wants_set', to='amc.character'),
        ),
    ]
