# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amc", "0203_wanted_set_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="wearing_costume",
            field=models.BooleanField(
                default=False,
                help_text="Tracks whether the character is currently wearing a costume (EquipmentSlot=4). Updated by ServerSetEquipmentInventory webhook.",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="costume_item_key",
            field=models.CharField(
                blank=True,
                help_text="Item key of the worn costume; NULL when not wearing one.",
                max_length=100,
                null=True,
            ),
        ),
    ]
