# Generated by Django migration

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amc", "0204_character_wearing_costume"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeleportPortal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "source",
                    django.contrib.gis.db.models.fields.PointField(dim=3, srid=0),
                ),
                (
                    "source_radius",
                    models.PositiveIntegerField(default=120),
                ),
                (
                    "target",
                    django.contrib.gis.db.models.fields.PointField(dim=3, srid=0),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
