# Generated by Django 5.2.3 on 2026-04-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0208_guild_vehicle_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildVehicleCargoRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_cargo_keys', models.JSONField(blank=True, default=list)),
                ('excluded_cargo_keys', models.JSONField(blank=True, default=list)),
                ('max_damage', models.FloatField(blank=True, null=True)),
                ('min_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('max_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('bonus_pct', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GuildVehiclePassengerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_passenger_types', models.JSONField(blank=True, default=list)),
                ('require_comfort', models.BooleanField(blank=True, null=True)),
                ('require_urgent', models.BooleanField(blank=True, null=True)),
                ('require_limo', models.BooleanField(blank=True, null=True)),
                ('require_offroad', models.BooleanField(blank=True, null=True)),
                ('min_comfort_rating', models.IntegerField(blank=True, null=True)),
                ('max_comfort_rating', models.IntegerField(blank=True, null=True)),
                ('bonus_pct', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameIndex(
            model_name='guildsession',
            new_name='amc_guildse_charact_27fe28_idx',
            old_name='guildsession_char_end_idx',
        ),
        migrations.AddField(
            model_name='guildsession',
            name='guild_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='amc.guildvehicle'),
        ),
        migrations.AddField(
            model_name='servercargoarrivedlog',
            name='guild_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_logs', to='amc.guildsession'),
        ),
        migrations.AddField(
            model_name='serverpassengerarrivedlog',
            name='guild_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_logs', to='amc.guildsession'),
        ),
        migrations.AddField(
            model_name='guildvehiclecargorequirement',
            name='guild_vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_requirement', to='amc.guildvehicle'),
        ),
        migrations.AddField(
            model_name='guildvehiclepassengerrequirement',
            name='guild_vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_requirement', to='amc.guildvehicle'),
        ),
    ]
