# Generated by Django 5.2.3 on 2026-04-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0209_guild_vehicle_work_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildvehiclepassengerrequirement',
            name='guild_vehicle',
        ),
        migrations.RemoveField(
            model_name='guildsession',
            name='guild_vehicle',
        ),
        migrations.CreateModel(
            name='GuildCargoRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_cargo_keys', models.JSONField(blank=True, default=list)),
                ('excluded_cargo_keys', models.JSONField(blank=True, default=list)),
                ('max_damage', models.FloatField(blank=True, null=True)),
                ('min_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('max_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('bonus_pct', models.PositiveIntegerField(default=0)),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_requirement', to='amc.guild')),
            ],
        ),
        migrations.CreateModel(
            name='GuildPassengerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_passenger_types', models.JSONField(blank=True, default=list)),
                ('require_comfort', models.BooleanField(blank=True, null=True)),
                ('require_urgent', models.BooleanField(blank=True, null=True)),
                ('require_limo', models.BooleanField(blank=True, null=True)),
                ('require_offroad', models.BooleanField(blank=True, null=True)),
                ('min_comfort_rating', models.IntegerField(blank=True, null=True)),
                ('max_comfort_rating', models.IntegerField(blank=True, null=True)),
                ('bonus_pct', models.PositiveIntegerField(default=0)),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_requirement', to='amc.guild')),
            ],
        ),
        migrations.DeleteModel(
            name='GuildVehicleCargoRequirement',
        ),
        migrations.DeleteModel(
            name='GuildVehiclePassengerRequirement',
        ),
    ]
