from django.db import migrations, models


def _add_telemetry_columns(cursor):
    cols = [
        ("yaw", "double precision"),
        ("speed", "double precision"),
        ("velocity_x", "double precision"),
        ("velocity_y", "double precision"),
        ("velocity_z", "double precision"),
        ("rpm", "double precision"),
        ("gear", "smallint"),
    ]
    for name, dtype in cols:
        cursor.execute(
            f"ALTER TABLE amc_characterlocation ADD COLUMN IF NOT EXISTS {name} {dtype}"
        )


def _create_fresh_hypertable(cursor):
    cursor.execute("""
        CREATE TABLE amc_characterlocation (
            id bigint GENERATED BY DEFAULT AS IDENTITY,
            "timestamp" timestamptz NOT NULL DEFAULT now(),
            character_id integer NOT NULL,
            location geometry(PointZ) NOT NULL,
            vehicle_key varchar(100),
            yaw double precision,
            speed double precision,
            velocity_x double precision,
            velocity_y double precision,
            velocity_z double precision,
            rpm double precision,
            gear smallint,
            CONSTRAINT amc_characterlocation_pkey PRIMARY KEY (id, "timestamp"),
            CONSTRAINT fk_charloc_character
                FOREIGN KEY (character_id) REFERENCES amc_character(id) ON DELETE CASCADE,
            CONSTRAINT unique_character_location
                UNIQUE ("timestamp", character_id)
        )
    """)
    cursor.execute("""
        SELECT create_hypertable('amc_characterlocation',
            by_range('timestamp', INTERVAL '1 month'))
    """)
    cursor.execute("""
        CREATE INDEX charloc_char_ts_idx
            ON amc_characterlocation (character_id, "timestamp" DESC)
    """)


def _enable_compression(cursor):
    cursor.execute("""
        ALTER TABLE amc_characterlocation SET (
            timescaledb.compress,
            timescaledb.compress_segmentby = 'character_id',
            timescaledb.compress_orderby = 'timestamp DESC'
        )
    """)
    cursor.execute(
        "SELECT add_compression_policy('amc_characterlocation', INTERVAL '7 days')"
    )


def _drop_old_table(cursor):
    cursor.execute("DROP TABLE IF EXISTS amc_characterlocation_old CASCADE")


def migrate_to_timescaledb(apps, schema_editor):
    from django.db import connection

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT relkind FROM pg_class WHERE relname = 'amc_characterlocation'"
        )
        row = cursor.fetchone()
        if not row:
            return

        relkind = row[0]

        if relkind == "r":
            cursor.execute(
                "ALTER TABLE amc_characterlocation "
                "DROP CONSTRAINT IF EXISTS amc_characterlocation_pkey"
            )
            _add_telemetry_columns(cursor)
            cursor.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
            cursor.execute("""
                SELECT create_hypertable('amc_characterlocation',
                    by_range('timestamp', INTERVAL '1 month'),
                    migrate_data => true, if_not_exists => true)
            """)
            cursor.execute(
                "ALTER TABLE amc_characterlocation "
                "ADD PRIMARY KEY (id, \"timestamp\")"
            )
            _enable_compression(cursor)

        elif relkind == "p":
            cursor.execute(
                "ALTER TABLE amc_characterlocation RENAME TO amc_characterlocation_archive"
            )
            cursor.execute(
                "ALTER TABLE amc_characterlocation_archive "
                "DROP CONSTRAINT IF EXISTS fk_charloc_character"
            )
            cursor.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
            _create_fresh_hypertable(cursor)
            _enable_compression(cursor)

        _drop_old_table(cursor)


class Migration(migrations.Migration):
    dependencies = [
        ("amc", "0210_guild_work_requirements_on_guild"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="characterlocation",
                    name="yaw",
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="characterlocation",
                    name="speed",
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="characterlocation",
                    name="velocity_x",
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="characterlocation",
                    name="velocity_y",
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="characterlocation",
                    name="velocity_z",
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="characterlocation",
                    name="rpm",
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="characterlocation",
                    name="gear",
                    field=models.SmallIntegerField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(migrate_to_timescaledb, migrations.RunPython.noop),
            ],
        ),
    ]
