# Generated by Django 5.2.3 on 2026-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0211_characterlocation_timescaledb'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
    ]
