# Generated by Django 5.2.3 on 2026-04-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0212_gameevent_auto_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='welcome_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
