# Generated by Django 5.2.3 on 2026-03-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc_finance", "0002_remove_account_player_account_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="npl_warning_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
