# Generated by Django 5.2.3 on 2026-03-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amc_finance", "0005_account_last_credit_score_evaluated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTreasurySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "treasury_balance",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "reserves_balance",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("total_income", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("surplus", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "wealth_tax_collected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "nirc_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Full treasury summary dict for this day"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Daily treasury snapshots",
                "ordering": ["-date"],
            },
        ),
    ]
