# Generated by Django 5.2.3 on 2025-11-21 08:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NCServerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("log_path", models.CharField(max_length=500, null=True)),
                (
                    "hostname",
                    models.CharField(default="asean-mt-server", max_length=100),
                ),
                ("tag", models.CharField(default="necesse", max_length=100)),
                ("text", models.TextField()),
                ("event_processed", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.search.SearchVector(
                            "text", config="english"
                        ),
                        name="nc_log_text_search_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("timestamp", "text"), name="nc_unique_event_log_entry"
                    )
                ],
            },
        ),
    ]
