# Generated by Django 5.2.3 on 2025-12-21 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("necesse", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ncserverlog",
            options={
                "verbose_name": "Server Log",
                "verbose_name_plural": "Server Logs",
            },
        ),
    ]
